/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import kontroler.Obrada;
import pomocno.HibernateUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Admin
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public  Izbornik () {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        /*
        Obrada<Smjer> o = new Obrada<>();
        
        Smjer s = new Smjer();
        s.setNaziv("Smjer " + String.valueOf(Math.random()).substring(3,7));
        o.save(s);
        
        List<Smjer> lista = o.createQuery("from Smjer a where a.obrisano=false");
        for (Smjer smjer : lista) {
            System.out.println(smjer.getNaziv());
        }
        
        
        Obrada<Polaznik> op = new Obrada<>();
        Polaznik p = new Polaznik();
        p.setPrezime("Polaznik");
        p.setIme(String.valueOf(Math.random()).substring(3,7));
        op.save(p);
        
         List<Polaznik> polaznici = op.getAll();
        for (Polaznik polaznik : polaznici) {
            System.out.println(polaznik.getPrezime() + " " + polaznik.getIme());
        }
        
        Obrada<Predavac> opredavac = new Obrada<>();
        Predavac pr = new Predavac();
        pr.setIme("Predavač");
        pr.setPrezime(String.valueOf(Math.random()).substring(3,7));
        
        opredavac.save(pr);
        //uništavam si MVC
        List<Predavac> predavaci = HibernateUtil.getSession().createQuery(
                "from Predavac a where a.obrisano=false and a.prezime not like :prezime")
                .setParameter("prezime", "%2%")
                .list();
        
        */
        
     /*    List<Predavac> predavaci = HibernateUtil.getSession().createQuery(
                "from Predavac a where a.obrisano=false and a.prezime not like :prezime")
                .setParameter("prezime", "%2%")
                .list();
    } /**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edunova APP");

        jMenu2.setText("Unos");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    
