/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import kontroler.EdunovaException;
import javax.swing.JOptionPane;
import model.Stanar;
import model.Trosak;
import kontroler.Obrada;
import java.awt.event.ActionEvent;
import model.Entitet;
import pomocno.HibernateUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import kontroler.ObradaStanar;







/**
 *
 * @author vanjus
 */
public class Stanari extends javax.swing.JFrame {

   
     private ObradaStanar obrada;
    /**
     * Creates new form Stanari
     */
    public Stanari() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        obrada = new ObradaStanar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaStanari = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObriši = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrojStana = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDug = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBrojClanova = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUvjet = new javax.swing.JTextField();
        btnTrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listaStanari.setFont(new java.awt.Font("AppleGothic", 0, 12)); // NOI18N
        listaStanari.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaStanariValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaStanari);

        jLabel6.setFont(new java.awt.Font("AppleGothic", 2, 13)); // NOI18N
        jLabel6.setText("Broj Clanova");

        btnDodaj.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObriši.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        btnObriši.setText("Obriši");
        btnObriši.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrišiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("AppleGothic", 2, 13)); // NOI18N
        jLabel3.setText("Ime");

        jLabel4.setFont(new java.awt.Font("AppleGothic", 2, 13)); // NOI18N
        jLabel4.setText("Prezime");

        txtBrojStana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojStanaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AppleGothic", 2, 13)); // NOI18N
        jLabel5.setText("Broj Stana");

        jLabel7.setFont(new java.awt.Font("AppleGothic", 2, 13)); // NOI18N
        jLabel7.setText("Dug");

        jLabel1.setText("Uvjet");

        txtUvjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUvjetActionPerformed(evt);
            }
        });

        btnTrazi.setText("Traži");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });
        btnTrazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTraziKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrazi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnObriši))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnPromjeni))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrojStana, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDug, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrazi))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBrojStana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBrojClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni))
                        .addGap(18, 18, 18)
                        .addComponent(btnObriši))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Stanar s = new Stanar();
        s=napuniObjekt(s);
         try {
             s = obrada.spremi(s);
         } catch (EdunovaException ex) {
             switch (ex.getKomponenta()) {
                 case "ime":
                     txtIme.requestFocus();
                     break;
                 case "broj stana":
                     txtBrojStana.requestFocus();
                     break;
                 case "prezime":
                     txtPrezime.requestFocus();
                     break;
                 case "broj članova":
                     txtBrojClanova.requestFocus();
                     break;
                 case "dug":
                     txtDug.requestFocus();
                     break;
                        
             }
            JOptionPane.showMessageDialog(getRootPane(), "Spremanje nije izvršeno, " + ex.getMessage());       

         }
       
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        try {
            Stanar s = listaStanari.getSelectedValue();
            if(s==null){
                return;
            }
            s=napuniObjekt(s);
            obrada.spremi(s);
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
        }
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void listaStanariValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaStanariValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        Stanar p = listaStanari.getSelectedValue();

        if (p == null) {
            return;
        }

        txtIme.setText(p.getIme());
        txtPrezime.setText(p.getPrezime());
        txtBrojStana.setText(p.getBrojStana());
        txtBrojClanova.setText(p.getBrojClanova());
        
    }//GEN-LAST:event_listaStanariValueChanged

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
       if(txtUvjet.getText().trim().length() == 0){
           JOptionPane.showMessageDialog(getRootPane(), "Obavezno uvjet pretraživanja");
           return;
       }    
        trazi();
       txtUvjet.requestFocus();
                               
    }//GEN-LAST:event_btnTraziActionPerformed

    private void txtUvjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUvjetActionPerformed
          
    }//GEN-LAST:event_txtUvjetActionPerformed

    private void btnTraziKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTraziKeyPressed
        if(txtUvjet.getText().trim().length() == 0){
           JOptionPane.showMessageDialog(getRootPane(), "Obavezno uvjet pretraživanja");
           return;
       }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            trazi();
        }
    }//GEN-LAST:event_btnTraziKeyPressed

    private void txtBrojStanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojStanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojStanaActionPerformed

    private void btnObrišiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrišiActionPerformed
        Stanar st = listaStanari.getSelectedValue();
        if(st==null){
            return;
        }
        obrada.obrisi(st);
    }//GEN-LAST:event_btnObrišiActionPerformed

    private void trazi() {
        int brojRezultata = 10;
        DefaultListModel<Stanar> model = new DefaultListModel<>();
        
        if (txtUvjet.getText().trim().length() == 0) {
            brojRezultata = 10;
        }
       List<Stanar> lista = obrada.getStanari(txtUvjet.getText(), brojRezultata);
        for (Stanar stanar : lista) {
            model.addElement(stanar);
        }
        listaStanari.setModel(model);
   
    }
    
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObriši;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Stanar> listaStanari;
    private javax.swing.JTextField txtBrojClanova;
    private javax.swing.JTextField txtBrojStana;
    private javax.swing.JTextField txtDug;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

      private Stanar napuniObjekt(Stanar s) {
          s.setIme((txtIme.getText()));
          s.setPrezime(txtPrezime.getText());
        s.setBrojStana(txtBrojStana.getText());
        s.setBrojClanova(txtBrojClanova.getText());
        if(txtDug.getText().trim().length()>0){
           s.setDug(new BigDecimal(txtDug.getText())); 
        }
        
        return s;  
      }
}
