/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import kontroler.Obrada;
import model.Trosak;

/**
 *
 * @author vanjus
 */
public class Troskovi extends javax.swing.JFrame {

    private Obrada<Trosak> obrada;

    public Troskovi() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        obrada = new Obrada<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMjeseci = new javax.swing.JComboBox<>();
        txtMjesecUGodini = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDrugiTrosak = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTrosakZaCiscenje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTrosakStubisnaRasvjeta = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromijeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnTrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbMjeseci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siječanj", "Veljača", "Ožujak", "Travanj", "Svibanj", "Lipanj", "Srpanj", "Kolovoz", "Rujan", "Listopad", "Studeni", "Prosinac" }));
        cmbMjeseci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMjeseciActionPerformed(evt);
            }
        });

        txtMjesecUGodini.setText("izaberi mjesec u godini");

        jLabel1.setText("unesi trošak za čišćenje");

        jLabel2.setText("unesi trošak za stubišnu rasvjetu");

        jLabel3.setText("unesi neki drugi trošak");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromijeni.setText("Promijeni");

        btnObrisi.setText("Obriši");

        btnTrazi.setText("Traži");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmbMjeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrazi))
                        .addComponent(txtTrosakStubisnaRasvjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTrosakZaCiscenje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtDrugiTrosak, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMjesecUGodini))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(34, 34, 34)
                        .addComponent(btnPromijeni)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnObrisi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtMjesecUGodini)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMjeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrazi))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTrosakZaCiscenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTrosakStubisnaRasvjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDrugiTrosak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnPromijeni))
                .addGap(18, 18, 18)
                .addComponent(btnObrisi)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMjeseciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMjeseciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMjeseciActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Trosak t = new Trosak();

        if (txtTrosakZaCiscenje.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(getRootPane(), "Unesi trosak ciscenja");
            return;
        }
        if (txtTrosakStubisnaRasvjeta.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(getRootPane(), "Unesi trosak stubisne rasvjete");
            return;
        }

        if (txtDrugiTrosak.getText().trim().length() > 0) {

            try {
                    t.setDodatniTrosak(new BigDecimal(txtDrugiTrosak.getText()));
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(getRootPane(), "drugi  trosak  nije broj");
     
                t.setDodatniTrosak(BigDecimal.ZERO);
            }

            
    }//GEN-LAST:event_btnDodajActionPerformed
        else{
             t.setDodatniTrosak(BigDecimal.ZERO);
        }
    try {
                new BigDecimal(txtTrosakZaCiscenje.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(getRootPane(), " trosak ciscenja nije broj");
                return;
            }
    
      try {
                new BigDecimal(txtTrosakStubisnaRasvjeta.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(getRootPane(), " trosak stubište nije broj");
                return;
            }

            t.setTrosakCiscenje(new BigDecimal(txtTrosakZaCiscenje.getText()));
            t.setTrosakStubisnaRasvjeta(new BigDecimal(txtTrosakStubisnaRasvjeta.getText()));
            t.setMjesecTroska(cmbMjeseci.getItemAt(WIDTH));
            

            obrada.save(t);
           
    
    }
     /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromijeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<String> cmbMjeseci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDrugiTrosak;
    private javax.swing.JLabel txtMjesecUGodini;
    private javax.swing.JTextField txtTrosakStubisnaRasvjeta;
    private javax.swing.JTextField txtTrosakZaCiscenje;
    // End of variables declaration//GEN-END:variables
}
